AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An app that sends a daily email message for each HSK level with a vocab word
Parameters:
  WordsBucketName:
    Type: String
  WordsBucketKey:
    Type: String
  ListsBucketName:
    Type: String
  ListsBucketKey:
    Type: String
  DomainName:
    Type: String
  SGApiKey:
    Type: String
  SubNotifyEmail:
    Type: String
  Stage:
    Type: String

Globals:
  Api:
    # Add AllowMethods with a list of methods for this domain name to call the API in this template
    Cors: !Sub "'${DomainName}'"

Resources:
  SendDailyCampaign:
    # A function that sends a daily SendGrid campaign with a vocab word for each HSK level
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub SendDailyCampaign-${Stage}
      Handler: SendDailyCampaign.lambda_handler
      Runtime: python3.7
      CodeUri: ./SendDailyCampaign
      Description: A function that sends a daily SendGrid campaign with a vocab word for each HSK level
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          SG_API_KEY: !Ref SGApiKey
          SUB_TOPIC_ARN: !Ref NotificationTopic
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
          LISTS_BUCKET_NAME: !Ref ListsBucketName
          LISTS_BUCKET_KEY: !Ref ListsBucketKey
          STAGE: !Ref Stage
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
      Layers:
       - !Ref Layer

  SampleVocabFunction:
    # A function that returns five random words for each HSK level
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub SampleVocabFunction-${Stage}
      Handler: SampleVocabFunction.lambda_handler
      Runtime: python3.7
      CodeUri: ./SampleVocabFunction
      Description: A function that returns five random words for each HSK level
      MemorySize: 128
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        SampleVocabFunctionApi:
          # An API Gateway endpoint that responds to HTTP GET
          Type: Api
          Properties:
            Path: /sample_vocab
            Method: GET
      Layers:
       - !Ref Layer
  
  SampleVocabLambdaPermission:
    # Permissions for API Gateway to invoke this function. Using a workaround described here:
    # https://github.com/awslabs/serverless-application-model/issues/59
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SampleVocabFunction
      Principal: apigateway.amazonaws.com

  SubscribeFunction:
    # A function that takes an HSK level and email address inputs and subscribes to a topic
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub SubscribeFunction-${Stage}
      Handler: SubscribeFunction.lambda_handler
      Runtime: python3.7
      CodeUri: ./SubscribeFunction
      Description: A function that takes an HSK level and email address inputs and subscribes to a topic.
      MemorySize: 128
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          SG_API_KEY: !Ref SGApiKey
          SUB_TOPIC_ARN: !Ref NotificationTopic
          LISTS_BUCKET_NAME: !Ref ListsBucketName
          LISTS_BUCKET_KEY: !Ref ListsBucketKey
          STAGE: !Ref Stage
      Events:
        SubscribeFunctionApi:
          # An API Gateway endpoint that responds to HTTP POST
          Type: Api
          Properties:
            Path: /sub
            Method: POST
      Layers:
       - !Ref Layer

  SubscribeLambdaPermission:
    # Permissions for API Gateway to invoke this function. Using a workaround described here:
    # https://github.com/awslabs/serverless-application-model/issues/59
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SubscribeFunction
      Principal: apigateway.amazonaws.com

  Layer:
    # A Layer that holds several Python modules
    # Contact lists returns the prod/staging SendGrid contact lists for each HSK level
    # Vocab random word returns a random word for a given HSK level
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: ./layer
      CompatibleRuntimes:
        - python3.7

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties: 
      TableName: !Sub DailyWordHistory-${Stage}
      AttributeDefinitions: 
        - AttributeName: Date
          AttributeType: N
        - AttributeName: Level
          AttributeType: N
      KeySchema: 
        - AttributeName: Date
          KeyType: HASH
        - AttributeName: Level
          KeyType: RANGE

  CWLogsNotifications:
    # A function that filters function logs for error messages and publishes to SNS
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - SubscribeFunctionLogGroup
      - SendDailyCampaignLogGroup
      - SampleVocabFunctionLogGroup
    Properties:
      FunctionName: !Sub CWLogsNotifications-${Stage}
      Handler: CWLogsNotifications.lambda_handler
      Runtime: python3.7
      CodeUri: ./CWLogsNotifications
      Description: A function that send notifications to an SNS topic for based on CW logs metric filters
      MemorySize: 128
      Timeout: 120
      Policies:
       - AWSLambdaExecute
       - SNSPublishMessagePolicy:
           TopicName: !GetAtt NotificationTopic.TopicName
      Environment:
        Variables:
          SUB_TOPIC_ARN: !Ref NotificationTopic
      Events:
        SubFunctionLogs:      
          Type: CloudWatchLogs
          Properties:
            LogGroupName: 
              !Join [
          '',
          ['/aws/lambda/', !Sub 'SubscribeFunction-${Stage}']
        ]
            FilterPattern: "?Error ?Success"
        SendDailyLogs:      
          Type: CloudWatchLogs
          Properties:
            LogGroupName: 
              !Join [
          '',
          ['/aws/lambda/', !Sub 'SendDailyCampaign-${Stage}']
        ]
            FilterPattern: Error
        SampleVocabLogs:      
          Type: CloudWatchLogs
          Properties:
            LogGroupName: 
              !Join [
          '',
          ['/aws/lambda/', !Sub 'SampleVocabFunction-${Stage}']
        ]
            FilterPattern: Error

  NotificationTopic:
    # A topic that error notifications will be published to
    Type: AWS::SNS::Topic
    Properties:
      Subscription: 
      - Protocol: email
        Endpoint: !Ref SubNotifyEmail

  # Creating CloudWatch Logs groups for each function. 
  # By default, a log group is only created for a function once the function is invoked.
  # We are creating log groups here to be able to subscribe the CWLogsNotification function to those log groups.
  SubscribeFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - SubscribeFunction
    Properties:
      LogGroupName: 
        !Join [
          '',
          ['/aws/lambda/', !Sub 'SubscribeFunction-${Stage}']
        ]

  SendDailyCampaignLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - SendDailyCampaign
    Properties:
      LogGroupName: 
        !Join [
          '',
          ['/aws/lambda/', !Sub 'SendDailyCampaign-${Stage}']
        ]
  
  SampleVocabFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - SampleVocabFunction
    Properties:
      LogGroupName: 
        !Join [
          '',
          ['/aws/lambda/', !Sub 'SampleVocabFunction-${Stage}']
        ]