AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An app that texts you an HSK vocab word each day and a link to example sentences.
Parameters:
  S3BucketName:
    Type: String
  S3BucketKey:
    Type: String
  SnsTopicArnLevel1:
    Type: String
  SnsTopicNameLevel1:
    Type: String
  SnsTopicArnLevel2:
    Type: String
  SnsTopicNameLevel2:
    Type: String
  SnsTopicArnLevel3:
    Type: String
  SnsTopicNameLevel3:
    Type: String
  SnsTopicArnLevel4:
    Type: String
  SnsTopicNameLevel4:
    Type: String
  SnsTopicArnLevel5:
    Type: String
  SnsTopicNameLevel5:
    Type: String    

Resources:
  TextFunction:
    # This function is triggered by a daily cloudwatch event at 12pm PST to call VocabRandomEntry
    # It publishes the results and a baidu URL with example sentences to an SNS topic
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TextFunction
      Handler: TextFunction.lambda_handler
      Runtime: python3.7
      CodeUri: ./TextFunction
      Description: A function that calls the VocabRandomEntry function and sends a text with response contents.
      Environment:
        Variables:
          SNS_TOPIC_ARN1: !Ref SnsTopicArnLevel1
          SNS_TOPIC_ARN2: !Ref SnsTopicArnLevel2
          SNS_TOPIC_ARN3: !Ref SnsTopicArnLevel3
          SNS_TOPIC_ARN4: !Ref SnsTopicArnLevel4
          SNS_TOPIC_ARN5: !Ref SnsTopicArnLevel5
          SNS_TOPIC_ARN6: !Ref SnsTopicArnLevel6
      Policies:
       - AWSLambdaExecute
       - AWSLambdaRole
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel1
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel2
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel3
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel4
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel5
       - SNSPublishMessagePolicy:
          TopicName: !Ref SnsTopicNameLevel6
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)

  VocabRandomEntry:
    # This function selects a random entry from an S3 file with HSK vocab
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: VocabRandomEntry
      Handler: VocabRandomEntry.lambda_handler
      Runtime: python3.7
      CodeUri: ./VocabRandomEntry
      Description: A function selects a random entry from a table.
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          S3_BUCKET_KEY: !Ref S3BucketKey
      Policies:
       - AWSLambdaExecute
       - AWSLambdaRole
  
  Level1Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: danielmweibel@gmail.com
          Protocol: sms
  
  Level2Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: danielmweibel@gmail.com
          Protocol: email