AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An app that texts you an HSK vocab word each day and a link to example sentences.
Parameters:
  S3BucketName:
    Type: String
  S3BucketKey:
    Type: String  

Resources:
  TextFunction:
    # This function is triggered by a daily cloudwatch event at 12pm PST to call VocabRandomEntry
    # It publishes the results and a baidu URL with example sentences to an SNS topic
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TextFunction
      Handler: TextFunction.lambda_handler
      Runtime: python3.7
      CodeUri: ./TextFunction
      Description: A function that calls the VocabRandomEntry function and sends a text with response contents.
      Environment:
        Variables:
          SNS_TOPIC_ARN1: !Ref Level1Topic
          SNS_TOPIC_ARN2: !Ref Level2Topic
          SNS_TOPIC_ARN3: !Ref Level3Topic
          SNS_TOPIC_ARN4: !Ref Level4Topic
          SNS_TOPIC_ARN5: !Ref Level5Topic
          SNS_TOPIC_ARN6: !Ref Level6Topic
      Policies:
       - AWSLambdaExecute
       - AWSLambdaRole
       - AmazonSNSFullAccess
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)

  VocabRandomEntry:
    # This function selects a random entry from an S3 file with HSK vocab
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: VocabRandomEntry
      Handler: VocabRandomEntry.lambda_handler
      Runtime: python3.7
      CodeUri: ./VocabRandomEntry
      Description: A function selects a random entry from a table.
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          S3_BUCKET_KEY: !Ref S3BucketKey
      Policies:
       - AWSLambdaExecute
       - AWSLambdaRole
  
  # SNS Topics at each HSK level
  Level1Topic:
    Type: AWS::SNS::Topic
  
  Level2Topic:
    Type: AWS::SNS::Topic
  
  Level3Topic:
    Type: AWS::SNS::Topic
  
  Level4Topic:
    Type: AWS::SNS::Topic
  
  Level5Topic:
    Type: AWS::SNS::Topic

  Level6Topic:
    Type: AWS::SNS::Topic