version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install awscli
          command: sudo pip install awscli
      
      - run:
          name: Install SAM
          command: pip install --user aws-sam-cli

      - run: 
          name: Deploy with SAM
          command: sam package --s3-bucket hsk-vocab --output-template-file packaged-template.yaml && sam deploy --template-file ./packaged-template.yaml --stack-name vocab --capabilities CAPABILITY_IAM --parameter-overrides S3BucketName=hsk-vocab S3BucketKey=HSK_Level_6.csv DomainName=https://haohaotiantian.com