version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install awscli
            pip install aws-sam-cli
            pip install coverage

      # - run:
      #     name: Run tests
      #     working_directory: src/tests/unit/
      #     command: coverage run -m unittest discover
        
      # - run:
      #     name: Run coverage report
      #     working_directory: src/tests/unit/
      #     command: coverage report -m

      - run: 
          name: Deploy with SAM
          command: |
            sam build && sam package --s3-bucket hsk-vocab --output-template-file packaged-template.yaml --region us-east-1

            if [ "${CIRCLE_BRANCH}" == "master" ]; then              
              sam deploy --template-file ./packaged-template.yaml --stack-name vocab --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides WordsBucketName=hsk-vocab WordsBucketKey=HSK_Level_6.csv ListsBucketName=hsk-vocab ListsBucketKey=Contact_Lists.csv DomainName=https://haohaotiantian.com OTPSecretKey=$OTPSecretKey DynamoBackupsS3BucketName=hhtt-backups AlarmEmail=$AlarmEmail TwitterConsumerKey=$TwitterConsumerKeyProd TwitterConsumerSecret=$TwitterConsumerSecretProd TwitterAccessToken=$TwitterAccessTokenProd TwitterAccessTokenSecret=$TwitterAccessTokenSecretProd Stage=prod
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              sam deploy --template-file ./packaged-template.yaml --stack-name vocab-staging --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides WordsBucketName=hsk-vocab-staging WordsBucketKey=HSK_Level_6.csv ListsBucketName=hsk-vocab-staging ListsBucketKey=Contact_Lists.csv DomainName=https://staging.haohaotiantian.com OTPSecretKey=$OTPSecretKey DynamoBackupsS3BucketName=hhtt-backups-staging AlarmEmail=$AlarmEmail TwitterConsumerKey=$TwitterConsumerKeyStaging TwitterConsumerSecret=$TwitterConsumerSecretStaging TwitterAccessToken=$TwitterAccessTokenStaging TwitterAccessTokenSecret=$TwitterAccessTokenSecretStaging Stage=staging
            fi