version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install awscli
          command: sudo pip install awscli
      
      - run:
          name: Install SAM
          command: sudo pip install aws-sam-cli

      - run: 
          name: Deploy with SAM
          command: |
            sam package --s3-bucket hsk-vocab --output-template-file packaged-template.yaml 
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then              
              sam deploy --template-file ./packaged-template.yaml --stack-name vocab --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides S3BucketName=hsk-vocab S3BucketKey=HSK_Level_6.csv DomainName=https://haohaotiantian.com SGApiKey=$SGApiKey SubNotifyEmail=$SubNotifyEmail Stage=Prod
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              sam deploy --template-file ./packaged-template.yaml --stack-name vocab-staging --region us-east-1 --capabilities CAPABILITY_IAM --parameter-overrides S3BucketName=hsk-vocab-staging S3BucketKey=HSK_Level_6.csv DomainName=https://staging.haohaotiantian.com SGApiKey=$SGApiKeyStaging SubNotifyEmail=$SubNotifyEmail Stage=Staging
            fi
           